### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by merwok** [da4089/py-xdrlib#1]
Hello!  The code in the stdlib was under the Python license (not the same thing as the PSF license).  I don’t think that this repo can just switch to MIT.

**Comment by da4089** [comment]
Agreed.  Where did you see a reference to the MIT license?

I don't understand the distinction between the Python license and the PSF license: do you mean that the Python license is the document including the BeOpen, CNRI, CWI, etc, licenses as well as the PSFv2 text?

**Comment by merwok** [comment]
Here: https://github.com/da4089/py-xdrlib/blob/main/pyproject.toml#L12

About Python vs PSF: I think I interpreted it wrong, the section here seems to declare clearly that Python 3.11 for example is under the PSF license: https://docs.python.org/3/license.html#psf-license

I am no lawyer and not part of any PSF licensing group.  Maybe the discussion (on Python forums) about moving old modules to PyPI should have a clear question to the PSF lawyer or members of the licensing and trademark group to get one definitive answer for all the repos!

**Comment by da4089** [comment]
Thanks -- clearly I missed that when setting up the project.  I've changed it to the PSF classifier now.  The LICENSE file itself was always PSF, and I've left it unchanged.

I'll see if I can get someone to speak authoritatively on Discourse re: what it _should_ be.

Thanks again!
